# 02__RunWorkload.py
# -----------------------------------------------------------------------------
# Azure Database for MySQL (8.4) load-test workload runner
#   - Database : gamedb_test
#   - Action   : Run CALL sp_test_item_update_outer() with high concurrency
#
# Version history: 
#   - v1.0 - 2026-06-19
#
# Architecture:
#   To avoid the Python GIL bottleneck (which leaves most DB sessions idle /
#   "Sleep"), the load is generated by MULTIPLE PROCESSES, each running MULTIPLE
#   THREADS. Total concurrency = PROCESSES x THREADS_PER_PROCESS.
#
# Usage:
#   1) Install package:  pip install mysql-connector-python
#   2) Run:              python 02__RunWorkload.py
#
#   Options (configurable via environment variables):
#        WORKLOAD_PROCESSES           Number of worker processes      (default = CPU count)
#        WORKLOAD_THREADS_PER_PROCESS Threads per process             (default 32)
#        WORKLOAD_DURATION_SEC        Time-based run in seconds       (default 300)
#        WORKLOAD_CALLS_PER_THREAD    Calls per thread when DURATION_SEC=0 (default 100)
# -----------------------------------------------------------------------------

import os
import sys
import time
import signal
import multiprocessing as mp
from datetime import datetime, timezone
from concurrent.futures import ThreadPoolExecutor, as_completed

import mysql.connector
from mysql.connector import errorcode

# -----------------------------------------------------------------------------
# Connection settings
# -----------------------------------------------------------------------------
DB_CONFIG = {
    "host"      : "####.mysql.database.azure.com",  # Configure your server name
    "port"      : 3306,
    "database"  : "gamedb_test",
    "user"      : "####",                           # Configure your username 
    "password"  : "####",                           # Configure your password
    # Azure Database for MySQL requires a TLS connection.
    "ssl_disabled": False,
    "connection_timeout": 30,
    # autocommit: the procedure performs COMMIT internally, so keep it True.
    "autocommit": True,
}

# -----------------------------------------------------------------------------
# Workload parameters
# -----------------------------------------------------------------------------
NUM_PROCESSES        = int(os.environ.get("WORKLOAD_PROCESSES"           , "8")) # Using multiple processes avoids the Python GIL bottleneck and allows all DB sessions to be active (not "Sleep")
THREADS_PER_PROCESS  = int(os.environ.get("WORKLOAD_THREADS_PER_PROCESS" , "32"))
CALLS_PER_THREAD     = int(os.environ.get("WORKLOAD_CALLS_PER_THREAD"    , "100000"))
DURATION_SEC         = float(os.environ.get("WORKLOAD_DURATION_SEC"      , "1440"))  # 0 disables time-based run

TOTAL_THREADS = NUM_PROCESSES * THREADS_PER_PROCESS

PROCEDURE_NAME = "sp_test_item_update_outer"

def _make_connection():
    """Create a single DB connection."""
    return mysql.connector.connect(**DB_CONFIG)


def worker(deadline, stop_event):
    """Repeatedly call the procedure using a single connection owned by this thread.

    Args:
        deadline: monotonic timestamp at which to stop, or None for call-count mode.
        stop_event: shared event; when set, the worker stops as soon as possible.

    Returns:
        (calls, errors): number of calls and errors performed by this thread
    """
    calls   = 0
    errors  = 0
    conn    = None
    cursor  = None

    try:
        conn = _make_connection()
        cursor = conn.cursor()

        while True:
            # Evaluate stop condition
            if stop_event.is_set():
                break
            if deadline is not None:
                if time.monotonic() >= deadline:
                    break
            else:
                if calls >= CALLS_PER_THREAD:
                    break

            try:
                cursor.execute(f"CALL {PROCEDURE_NAME}()")
                # Drain any result sets produced by the procedure call.
                while cursor.nextset():
                    pass
                calls += 1
            except mysql.connector.Error as e:
                errors += 1
                # If the connection was lost, try to reconnect; otherwise (deadlock / lock timeout, etc.) continue to the next loop.
                if e.errno in (errorcode.CR_SERVER_LOST, errorcode.CR_SERVER_GONE_ERROR):
                    try:
                        if cursor:
                            cursor.close()
                        if conn:
                            conn.close()
                        conn = _make_connection()
                        cursor = conn.cursor()
                    except mysql.connector.Error:
                        break
    except mysql.connector.Error as e:
        print(f"[worker] connection failed: {e}", file=sys.stderr)
    finally:
        if cursor is not None:
            try:
                cursor.close()
            except mysql.connector.Error:
                pass
        if conn is not None:
            try:
                conn.close()
            except mysql.connector.Error:
                pass

    return calls, errors


def process_main(process_index, stop_event, result_queue):
    """Entry point for a single worker process: spawns THREADS_PER_PROCESS threads.

    The child process ignores SIGINT (Ctrl+C); shutdown is driven by the parent
    via the shared stop_event so cleanup is coordinated.
    """
    # Let the parent own Ctrl+C; children stop via stop_event.
    signal.signal(signal.SIGINT, signal.SIG_IGN)

    # Compute the deadline locally so each process uses its own clock.
    deadline = (time.monotonic() + DURATION_SEC) if DURATION_SEC > 0 else None

    proc_calls = 0
    proc_errors = 0

    with ThreadPoolExecutor(max_workers=THREADS_PER_PROCESS) as pool:
        futures = [pool.submit(worker, deadline, stop_event) for _ in range(THREADS_PER_PROCESS)]
        for f in as_completed(futures):
            c, e = f.result()
            proc_calls += c
            proc_errors += e

    result_queue.put((proc_calls, proc_errors))


def main():
    # Pre-flight connection test (quick validation of credentials/network)
    try:
        test_conn = _make_connection()
        test_conn.close()
    except mysql.connector.Error as e:
        print(f"DB connection test failed: {e}", file=sys.stderr)
        return 1

    if DURATION_SEC > 0:
        mode = f"time-based {DURATION_SEC:.0f}s"
    else:
        mode = f"{CALLS_PER_THREAD} calls per thread"

    print("=" * 70)
    print(f"  Target server      : {DB_CONFIG['host']}")
    print(f"  Database           : {DB_CONFIG['database']}  /  User: {DB_CONFIG['user']}")
    print(f"  Procedure          : CALL {PROCEDURE_NAME}()")
    print(f"  Processes          : {NUM_PROCESSES}")
    print(f"  Threads / process  : {THREADS_PER_PROCESS}")
    print(f"  Total concurrency  : {TOTAL_THREADS}")
    print(f"  Run mode           : {mode}")
    print("  (Press Ctrl+C to stop early)")
    print("=" * 70)

    stop_event = mp.Event()
    result_queue = mp.Queue()
    processes = []

    wall_start = time.monotonic()
    start_utc = datetime.now(timezone.utc)
    print(f"  Start time (UTC)   : {start_utc.strftime('%Y-%m-%d %H:%M:%S')} UTC")

    for i in range(NUM_PROCESSES):
        p = mp.Process(target=process_main, args=(i, stop_event, result_queue))
        p.start()
        processes.append(p)

    interrupted = False
    try:
        # Wait for all processes; keep the main thread responsive to Ctrl+C.
        while any(p.is_alive() for p in processes):
            for p in processes:
                p.join(timeout=0.2)
    except KeyboardInterrupt:
        interrupted = True
        print("\nInterrupt requested - signalling workers to stop...", file=sys.stderr)
        stop_event.set()

        # Give workers a short grace period to finish the current call, then force-kill.
        grace_deadline = time.monotonic() + 10
        for p in processes:
            remaining = max(0.0, grace_deadline - time.monotonic())
            p.join(timeout=remaining)
        for p in processes:
            if p.is_alive():
                print(f"  force-terminating pid {p.pid}", file=sys.stderr)
                p.terminate()
        for p in processes:
            p.join()

    elapsed = time.monotonic() - wall_start
    end_utc = datetime.now(timezone.utc)

    # Drain whatever results made it into the queue.
    total_calls = 0
    total_errors = 0
    while not result_queue.empty():
        c, e = result_queue.get()
        total_calls += c
        total_errors += e

    print("-" * 70)
    if interrupted:
        print("  (run was interrupted; totals reflect completed work only)")
    print(f"  Start time (UTC)      : {start_utc.strftime('%Y-%m-%d %H:%M:%S')} UTC")
    print(f"  End time (UTC)        : {end_utc.strftime('%Y-%m-%d %H:%M:%S')} UTC")
    print(f"  Total procedure calls : {total_calls:,}")
    print(f"  Total errors          : {total_errors:,}")
    print(f"  Total elapsed time    : {elapsed:.2f} s")
    if elapsed > 0:
        print(f"  Throughput (TPS)      : {total_calls / elapsed:,.1f} calls/sec")
    print("=" * 70)

    return 130 if interrupted else 0


if __name__ == "__main__":
    sys.exit(main())

